version: '3.1' # specify docker-compose version

volumes:
  # Set up with `docker volume create ...`. See docker/README.md for more info.
  comp_ai_volume:
    external: true
  pg_comp_ai_volume:

services:
  # Runs from the latest release
  comp-ai-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pascalhuerten/comp-ai-api:v2.0.0
    pull_policy: always
    restart: always
    volumes:
      - comp_ai_volume:/data
      - ./data/models:/models
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:7680"
    depends_on:
      - postgres

  # Starts up a postgres database
  postgres:
    image: postgres
    restart: always
    volumes:
      - pg_comp_ai_volume:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres